### ISSUE TITLE
Discussion translatey(2px)

### ISSUE THREAD

**Issue by JapSeyz** [arsenaltech/nova-tab#5]
Hey, what's the thinking behind lowering the tabs down into the other tabs' content with translateY(2)?

**Comment by shabbirbharmal** [comment]
Not sure if I understand what you mean. Can you please elaborate?

**Comment by XGhozt** [comment]
I changed my tabs to look like this. Should I put in a merge request? I'm sorry @shabbirbharmal but the default tab design could be improved. I'm just glad we have tabs in Nova though, your package is great!

![image](https://user-images.githubusercontent.com/5670495/46631417-31bf7380-cafc-11e8-9fd1-b557a03f877a.png)

_**Edit:** I also removed the animation almost completely because it just makes tabs "feel slow" to the end user. But you can easily do this yourself._

**Comment by shabbirbharmal** [comment]
Would appreciate a pull request if you have already made changes. Thank you!

**Comment by XGhozt** [comment]
I've submitted the pull request.
I don't usually contribute much on github, so hopefully I've done it correctly.

**Comment by shabbirbharmal** [comment]
Looks great. Thanks!
